; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	USB @ ^2.0.0
	NimBLE-Arduino
	;ESP32-BLE-CompositeHID
	https://github.com/EmileSpecialProducts/ESP32-BLE-CompositeHID.git
	Callback
    olikraus/U8g2@^2.36.2

build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-DBOARD_DEVKITC
	-std=c++17

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

[env:mydevkit_esp32s3_debug]
platform = espressif32
board = esp32-s3-devkitc-1
; board = rymcu-esp32-s3-devkitc-1
framework = arduino
build_type = debug
lib_deps = 
	USB @ ^2.0.0

build_flags = 
	-DMY_DEVKIT
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DCORE_DEBUG_LEVEL=1
	-std=c++17

board_upload.flash_size = 8MB

[env:mydevkit_esp32s3_release]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_type = release
lib_deps = 
	USB @ ^2.0.0

build_flags = 
	-DMY_DEVKIT
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-std=c++17
	-Os
	-DNDEBUG

board_upload.flash_size = 8MB

[env:mydevkit_esp32s3_n16r8_release]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_type = release
lib_deps = 
	USB @ ^2.0.0

build_flags = 
	-DMY_DEVKIT
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-std=c++17
	-Os
	-DNDEBUG

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB

[env:nologo_esp32s3_n16r8_release]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_type = release
lib_deps = 
	USB @ ^2.0.0

build_flags = 
	-DBOARD_NOLOGO
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-std=c++17
	-Os
	-DNDEBUG

[env:nologo_esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_type = release
lib_deps = 
	USB @ ^2.0.0
	; NimBLE-Arduino
	; ESP32-BLE-CompositeHID
	; Callback
    ; olikraus/U8g2@^2.36.2


build_flags = 
	; -DCONFIG_FREERTOS_UNICORE
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-DBOARD_NOLOGO
	-std=c++17
	-Os
	-DNDEBUG

board_upload.flash_size = 8MB

[env:nologo_esp32s3-dev]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
build_type = debug
lib_deps = 
	USB @ ^2.0.0

build_flags = 
	; -DCONFIG_FREERTOS_UNICORE
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	; -DARDUINO_USB_MODE=0
	-DCORE_DEBUG_LEVEL=1
	-DBOARD_NOLOGO
	-std=c++17

; debug_init_break = tbreak setup
monitor_speed = 115200

board_upload.flash_size = 8MB

[env:walnutpi]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	USB @ ^2.0.0
	; NimBLE-Arduino
	; ESP32-BLE-CompositeHID
	; Callback
    ; olikraus/U8g2@^2.36.2


build_flags = 
	; -DCONFIG_FREERTOS_UNICORE
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-DBOARD_WALNUT
	-std=c++17

board_upload.flash_size = 8MB

[env:esp32-c3-devkitm-1]
platform = espressif32
board_build.flash_mode = dio
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200

[env:luluhui-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
lib_deps = 
	USB @ ^2.0.0
	NimBLE-Arduino
	;ESP32-BLE-CompositeHID
	https://github.com/EmileSpecialProducts/ESP32-BLE-CompositeHID.git
	Callback
    olikraus/U8g2@^2.36.2

build_flags = 
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-DMY_DEVKIT
	-std=c++17

board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 8MB